### ISSUE TITLE
help

### ISSUE THREAD

**Issue by coleak2021** [davor10105/MaliciousURLDetection#2]
Can you provide me with the dataset, please?

**Comment by davor10105** [comment]
Hey @coleak2021 , this was done quite a while ago so I do not know the exact dataset used. However, you can just use this dataset: https://www.kaggle.com/datasets/sid321axn/malicious-urls-dataset and remap the labels so that 'benign' = 'good' and everything else = 'bad'. The rest of the code should be working as expected.
Let me know if you need additional help.
